#!/usr/bin/env ruby

require_relative 'lib/metrics_to_datadog'

app_key =ENV['DATADOG_APP_KEY']
api_key = ENV['DATADOG_API_KEY']
dashboard_config = ARGV[0]

if app_key.nil? || api_key.nil? then
  puts "Please set DATADOG_APP_KEY and DATADOG_APP_KEY with your datadog credentials"
  exit 1
end

if dashboard_config.nil? then
  puts "Usage: import_static_screenboard /path/to/dashboard.json"
  exit 1
end

metrics = MetricsToDatadog.new(app_key, api_key)
p metrics.set_dashboard(dashboard_config)
